/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface HelloWorldComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
}

declare global {


  interface HTMLHelloWorldComponentElement extends Components.HelloWorldComponent, HTMLStencilElement {}
  var HTMLHelloWorldComponentElement: {
    prototype: HTMLHelloWorldComponentElement;
    new (): HTMLHelloWorldComponentElement;
  };
  interface HTMLElementTagNameMap {
    'hello-world-component': HTMLHelloWorldComponentElement;
  }
}

declare namespace LocalJSX {
  interface HelloWorldComponent {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }

  interface IntrinsicElements {
    'hello-world-component': HelloWorldComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'hello-world-component': LocalJSX.HelloWorldComponent & JSXBase.HTMLAttributes<HTMLHelloWorldComponentElement>;
    }
  }
}


